server:
  port: 8082
spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    open-in-view: true
#    defer-datasource-initialization: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/challenge03_microservices
#    username: postgres
#    password: password
  application:
    name: ms-notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: partyhelper.repost@gmail.com
    password: vbkovjcxgzmkznzt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      indent-output: true
